# Generated by Django 2.2.7 on 2019-11-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_yourmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='phone',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
